---
title: "확률및통계학-R실습"
output: word_document
---


## grass CO2
# one-sample t-test

```{r}
data(CO2)
t.test(CO2$uptake,mu=30) # mu이 모집단 평균, 모수 / 양측검정
t.test(CO2$uptake,mu=30,alternative="greater") # / one way 크다
t.test(CO2$uptake,mu=30,alternative="less") # 작다에 대한 one way

mean(CO2$uptake)
sd(CO2$uptake)
var(CO2$uptake)
length(CO2$uptake)
```

# two-sample t-test

```{r}
tapply(CO2$uptake,CO2$Type,mean)
tapply(CO2$uptake,CO2$Type,sd)
t.test(uptake~Type,data = CO2)
```

# paired t-test

```{r}
swim <- read.csv("./data/ch9_swim.csv")  
head(swim)
t.test(swim$self,swim$rival)
t.test(swim$self,swim$rival,paired=TRUE)
```

# 연습문제 9-1

```{r}
spray <- read.csv("./data/ex9-1.csv")  
head(spray)
tapply(spray$Y,spray$treatment,mean)
tapply(spray$Y,spray$treatment,sd)
t.test(Y~treatment,data = spray)
t.test(Y~treatment,data = spray,var.equal=TRUE)
```


# 연습문제 9-3

```{r}
bodytemp <- read.csv("./data/ch9_bodytemp.csv")  
head(bodytemp)
x <- bodytemp$men
y <- bodytemp$women


xbar<-mean(x)
s1<-sd(x)
n1<-length(x)

ybar<-mean(y)
s2<-sd(y)
n2 <- length(y)

sp <- sqrt(((n1-1)*s1**2+(n2-1)*s2**2)/(n1+n2-2))
se <- sp*sqrt(1/n1+1/n2)

t = (xbar-ybar)/se
t
pvalue <- 2*(1-pt(abs(t),df=n1+n2-2))
pvalue

2*(1-pnorm(abs(t)))

t.test(bodytemp$men,bodytemp$women)
t.test(bodytemp$men,bodytemp$women,var.equal=TRUE)


```
